package com.iplan.iplant;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class iplant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String folio;
	private java.lang.String instrumento;
	private java.lang.String noContrato;
	private java.lang.String noCliente;
	private java.lang.String producto;

	private com.iplan.iplant.rechazar rechazar;

	private com.iplan.iplant.reviar revisar;

	public iplant() {
	}

	public java.lang.String getFolio() {
		return this.folio;
	}

	public void setFolio(java.lang.String folio) {
		this.folio = folio;
	}

	public java.lang.String getInstrumento() {
		return this.instrumento;
	}

	public void setInstrumento(java.lang.String instrumento) {
		this.instrumento = instrumento;
	}

	public java.lang.String getNoContrato() {
		return this.noContrato;
	}

	public void setNoContrato(java.lang.String noContrato) {
		this.noContrato = noContrato;
	}

	public java.lang.String getNoCliente() {
		return this.noCliente;
	}

	public void setNoCliente(java.lang.String noCliente) {
		this.noCliente = noCliente;
	}

	public java.lang.String getProducto() {
		return this.producto;
	}

	public void setProducto(java.lang.String producto) {
		this.producto = producto;
	}

	public com.iplan.iplant.rechazar getRechazar() {
		return this.rechazar;
	}

	public void setRechazar(com.iplan.iplant.rechazar rechazar) {
		this.rechazar = rechazar;
	}

	public com.iplan.iplant.reviar getRevisar() {
		return this.revisar;
	}

	public void setRevisar(com.iplan.iplant.reviar revisar) {
		this.revisar = revisar;
	}

	public iplant(java.lang.String folio, java.lang.String instrumento,
			java.lang.String noContrato, java.lang.String noCliente,
			java.lang.String producto, com.iplan.iplant.rechazar rechazar,
			com.iplan.iplant.reviar revisar) {
		this.folio = folio;
		this.instrumento = instrumento;
		this.noContrato = noContrato;
		this.noCliente = noCliente;
		this.producto = producto;
		this.rechazar = rechazar;
		this.revisar = revisar;
	}

}