package com.iplan.iplant;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class rechazar implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String estatusContrato;
	private java.lang.Boolean terminar;
	private java.lang.String causaRechazoContrato;

	public rechazar() {
	}

	public java.lang.String getEstatusContrato() {
		return this.estatusContrato;
	}

	public void setEstatusContrato(java.lang.String estatusContrato) {
		this.estatusContrato = estatusContrato;
	}

	public java.lang.Boolean getTerminar() {
		return this.terminar;
	}

	public void setTerminar(java.lang.Boolean terminar) {
		this.terminar = terminar;
	}

	public java.lang.String getCausaRechazoContrato() {
		return this.causaRechazoContrato;
	}

	public void setCausaRechazoContrato(java.lang.String causaRechazoContrato) {
		this.causaRechazoContrato = causaRechazoContrato;
	}

	public rechazar(java.lang.String estatusContrato,
			java.lang.Boolean terminar, java.lang.String causaRechazoContrato) {
		this.estatusContrato = estatusContrato;
		this.terminar = terminar;
		this.causaRechazoContrato = causaRechazoContrato;
	}

}