package com.iplan.iplant;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class reviar implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String estatusContrato;
	private java.lang.Boolean actualizar;
	private java.lang.Boolean rechazar;
	private java.lang.Boolean aprobar;
	private String nombreTitular;

	public reviar() {
	}

	public java.lang.String getEstatusContrato() {
		return this.estatusContrato;
	}

	public void setEstatusContrato(java.lang.String estatusContrato) {
		this.estatusContrato = estatusContrato;
	}

	public java.lang.Boolean getActualizar() {
		return this.actualizar;
	}

	public void setActualizar(java.lang.Boolean actualizar) {
		this.actualizar = actualizar;
	}

	public java.lang.Boolean getRechazar() {
		return this.rechazar;
	}

	public void setRechazar(java.lang.Boolean rechazar) {
		this.rechazar = rechazar;
	}

	public java.lang.Boolean getAprobar() {
		return this.aprobar;
	}

	public void setAprobar(java.lang.Boolean aprobar) {
		this.aprobar = aprobar;
	}

	public java.lang.String getNombreTitular() {
		return this.nombreTitular;
	}

	public void setNombreTitular(java.lang.String nombreTitular) {
		this.nombreTitular = nombreTitular;
	}

	public reviar(java.lang.String estatusContrato,
			java.lang.Boolean actualizar, java.lang.Boolean rechazar,
			java.lang.Boolean aprobar, java.lang.String nombreTitular) {
		this.estatusContrato = estatusContrato;
		this.actualizar = actualizar;
		this.rechazar = rechazar;
		this.aprobar = aprobar;
		this.nombreTitular = nombreTitular;
	}

}